name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 添加權限設定
    permissions:
      contents: read
      pages: write
      id-token: write
    # 確保在 GitHub Pages 環境中運行
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Generate static site
        run: |
          export NODE_ENV=production
          export APP_BASEURL=https://paul-1997.github.io/Hex-nuxt-enjoyHotel-dev/
          pnpm generate
        env:
          NODE_ENV: production
          APP_BASEURL: https://paul-1997.github.io/Hex-nuxt-enjoyHotel-dev/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          # 使用你的 Personal Access Token
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          # 添加部署訊息
          commit_message: "Deploy to GitHub Pages"
          full_name: "GitHub Actions"
          email: "actions@github.com" 